-- This program is to check String constant length and null in the string 
class Main {
	main():IO {
		int n,fact,i;
		String a ="Hello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\n";
		new IO.out_string("Hello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\nHello \0 world!\n")
		
	};
};
